apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
patches:
  - target:
      kind: Namespace
      name: local-path-storage
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: local-path-storage