repositories:
  # - name: rancher-stable
  #   url: https://releases.rancher.com/server-charts/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  # - name: open-webui
  #   url: https://ghcr.io/open-webui/helm-charts

releases:
  # - name: rancher
  #   namespace: cattle-system
  #   chart: rancher-stable/rancher
  #   version: 2.7.9
  #   values:
  #     - helm-configs/cattle-system/rancher/values.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.2
    values:
      - helm-configs/ingress-nginx/ingress-nginx/values.yaml

  - name: dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.12.0
    values:
      - helm-configs/kubernetes-dashboard/dashboard/values.yaml
    hooks:
      - events: 
          - postsync
        showlogs: true
        command: kubectl
        args: 
          - apply
          - --filename
          - kube-configs/kubernetes-dashboard/crs.yaml

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.9
    values:
      - helm-configs/metallb-system/metallb/values.yaml
    hooks:
      - events: 
          - postsync
        showlogs: true
        command: kubectl
        args: 
          - apply
          - --filename
          - kube-configs/metallb-system/crs.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 72.5.3
    values:
      - helm-configs/monitoring/kube-prometheus-stack/values.yaml
  
  - name: local-path-provisioner
    namespace: local-path-storage
    createNamespace: true
    chart: kube-configs/local-path-storage

  # - name: loki
  #   namespace: monitoring
  #   chart: grafana/loki
  #   version: 5.44.0
  #   values:
  #     - helm-configs/monitoring/loki/values.yaml

  # - name: promtail
  #   namespace: monitoring
  #   chart: grafana/promtail
  #   version: 6.15.0
  #   values:
  #     - helm-configs/monitoring/promtail/values.yaml

  # - name: open-webui
  #   namespace: open-webui
  #   chart: open-webui/open-webui
  #   version: 0.1.28
  #   values:
  #     - helm-configs/open-webui/open-webui-values.yaml