apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: longhorn
resources: 
  - ../../base/controllers
patches:
  # - path: disable-cert-manager.yaml
  #   target:
  #     kind: HelmRelease
  #     name: cert-manager
  #     namespace: cert-manager
  - path: disable-longhorn.yaml
    target:
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  - path: disable-metallb.yaml
    target:
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
  - path: disable-traefik.yaml
    target:
      kind: HelmRelease
      name: traefik
      namespace: traefik