# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: podinfo
# resources:
#   - ../base/monitoring
# patches:
#   - path: monitoring-values.yaml
#     target:
#       kind: HelmRelease
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami
resources:
  - ../base/whoami