apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=72.6.1"
  test:
    enable: false
  values:
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.staging.fplabs.lan