apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: longhorn
resources: 
  - ../../base/controllers
patches:
  - path: disable-longhorn.yaml
    target:
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system